sssom_validation:
  stage: test
  image: obolibrary/odkfull:v1.4
  rules:
    # Run for:
    #    Branch pipelines for main when a merge request is not open for the branch.
    #    Merge request pipelines when a merge request is open for the branch.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  # Script defines a sequence of tasks that will be executed as part of the job
  script:
    # Install latest SSSOM
    - pip install --upgrade pip && pip install -U sssom
    # Run mapping QC checks
    - make validate-mappings